//! Generates the decorative-art asset list at build time.
//!
//! Dropping a new PNG into `assets/art/<category>/` is enough to make it
//! available to the app: the generated module embeds every file with
//! `include_bytes!`, so there is no per-asset code to maintain.

use std::{env, fs, path::Path};

fn main() {
    println!("cargo:rerun-if-changed=assets/art");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let mut generated = String::from("// @generated by build.rs — do not edit.\n");

    for category in ["portraits", "emblems", "avatars"] {
        let directory = Path::new("assets/art").join(category);
        let mut entries: Vec<String> = Vec::new();
        if let Ok(read) = fs::read_dir(&directory) {
            for entry in read.flatten() {
                let path = entry.path();
                if path.extension().and_then(|ext| ext.to_str()) != Some("png") {
                    continue;
                }
                let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
                    continue;
                };
                let relative = format!("/assets/art/{category}/{stem}.png");
                entries.push(format!(
                    "    (\"{stem}\", include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"{relative}\"))),"
                ));
            }
        }
        entries.sort();
        let constant = category.to_uppercase();
        generated.push_str(&format!(
            "\n#[allow(dead_code, reason = \"generated asset list\")]\npub static {constant}: &[(&str, &[u8])] = &[\n{}\n];\n",
            entries.join("\n")
        ));
    }

    fs::write(Path::new(&out_dir).join("art_assets.rs"), generated)
        .expect("write generated asset list");
}
